apiVersion: 1

datasources:
  - name: MM-API
    type: simplejson
    access: proxy
    url: http://host.docker.internal:8080
    isDefault: false
    jsonData:
      httpMethod: GET
    editable: true
