#!/usr/bin/env python3
"""
Plot early linear rate discrimination between kilonovae and supernovae.

Reads data from /tmp/early_rate_discrimination.dat (generated by
cargo test -p mm-core --test test_early_rate_discrimination -- --nocapture)

Produces: assets/early_rate_discrimination.png
"""

import numpy as np
import matplotlib.pyplot as plt
from pathlib import Path

# ── Load data ────────────────────────────────────────────────────────

data_path = Path("/tmp/early_rate_discrimination.dat")
if not data_path.exists():
    print("Data file not found. Run:")
    print("  cargo test -p mm-core --test test_early_rate_discrimination -- --nocapture")
    exit(1)

classes = {"KN": [], "SNIa": [], "SNII": []}
with open(data_path) as f:
    for line in f:
        if line.startswith("#"):
            continue
        parts = line.strip().split()
        if len(parts) != 4:
            continue
        label = parts[0]
        rise, decay, mult = float(parts[1]), float(parts[2]), float(parts[3])
        if label in classes:
            classes[label].append((rise, decay, mult))

for k in classes:
    classes[k] = np.array(classes[k])

# ── Styling ──────────────────────────────────────────────────────────

colors = {"KN": "#e74c3c", "SNIa": "#3498db", "SNII": "#2ecc71"}
labels = {"KN": "Kilonova", "SNIa": "SN Ia", "SNII": "SN II"}

fig, axes = plt.subplots(2, 2, figsize=(12, 10))
fig.suptitle(
    "Early Linear Rate Discriminator: Kilonova vs Supernova\n"
    "(500 per class, ZTF-like 1-3 day cadence, first 3 days)",
    fontsize=14, fontweight="bold",
)

# ── Panel 1: Rise rate distributions ────────────────────────────────

ax = axes[0, 0]
bins = np.linspace(0, 1.5, 40)
for k in ["KN", "SNIa", "SNII"]:
    vals = classes[k][:, 0]
    vals = vals[np.isfinite(vals)]
    ax.hist(vals, bins=bins, alpha=0.6, label=labels[k], color=colors[k],
            density=True, histtype="stepfilled", edgecolor="black", linewidth=0.5)

# Threshold lines
ax.axvline(0.5, color="gray", linestyle="--", linewidth=1.5, label="SN max (0.5)")
ax.axvline(1.0, color="gray", linestyle=":", linewidth=1.5, label="KN min (1.0)")
ax.set_xlabel("Rise Rate (mag/day)", fontsize=12)
ax.set_ylabel("Density", fontsize=12)
ax.set_title("Rise Rate Distributions", fontsize=12)
ax.legend(fontsize=9)
ax.set_xlim(0, 1.5)

# ── Panel 2: Decay rate distributions ───────────────────────────────

ax = axes[0, 1]
bins = np.linspace(0, 2.0, 40)
for k in ["KN", "SNIa", "SNII"]:
    vals = classes[k][:, 1]
    vals = vals[np.isfinite(vals)]
    ax.hist(vals, bins=bins, alpha=0.6, label=labels[k], color=colors[k],
            density=True, histtype="stepfilled", edgecolor="black", linewidth=0.5)

ax.axvline(0.3, color="gray", linestyle="--", linewidth=1.5, label="KN min decay (0.3)")
ax.set_xlabel("Decay Rate (mag/day)", fontsize=12)
ax.set_ylabel("Density", fontsize=12)
ax.set_title("Decay Rate Distributions", fontsize=12)
ax.legend(fontsize=9)
ax.set_xlim(0, 2.0)

# ── Panel 3: Rise vs Decay scatter ─────────────────────────────────

ax = axes[1, 0]
for k in ["SNIa", "SNII", "KN"]:  # Plot KN on top
    d = classes[k]
    mask = np.isfinite(d[:, 0]) & np.isfinite(d[:, 1])
    ax.scatter(d[mask, 0], d[mask, 1], alpha=0.3, s=15,
               color=colors[k], label=labels[k], edgecolors="none")

# Threshold box
ax.axvline(0.5, color="gray", linestyle="--", linewidth=1, alpha=0.7)
ax.axhline(0.3, color="gray", linestyle="--", linewidth=1, alpha=0.7)
ax.axvline(1.0, color="gray", linestyle=":", linewidth=1, alpha=0.7)

# Label regions
ax.text(0.25, 1.6, "SN zone\n(slow rise)", ha="center", fontsize=9, color="gray",
        fontstyle="italic")
ax.text(1.2, 1.6, "KN zone\n(fast rise +\nfast decay)", ha="center", fontsize=9,
        color="#e74c3c", fontstyle="italic")

ax.set_xlabel("Rise Rate (mag/day)", fontsize=12)
ax.set_ylabel("Decay Rate (mag/day)", fontsize=12)
ax.set_title("Rise vs Decay Rate", fontsize=12)
ax.legend(fontsize=9, loc="upper right")
ax.set_xlim(0, 1.5)
ax.set_ylim(0, 2.0)

# ── Panel 4: FAR multiplier distributions ───────────────────────────

ax = axes[1, 1]
bins = np.linspace(0, 8, 30)
for k in ["KN", "SNIa", "SNII"]:
    vals = classes[k][:, 2]
    vals = vals[np.isfinite(vals)]
    ax.hist(vals, bins=bins, alpha=0.6, label=labels[k], color=colors[k],
            density=True, histtype="stepfilled", edgecolor="black", linewidth=0.5)

ax.axvline(1.0, color="black", linestyle="-", linewidth=2, label="Neutral (1.0)")
ax.set_xlabel("FAR Multiplier", fontsize=12)
ax.set_ylabel("Density", fontsize=12)
ax.set_title("FAR Multiplier (>1 = penalized, <1 = boosted)", fontsize=12)
ax.legend(fontsize=9)

# ── Summary annotation ──────────────────────────────────────────────

summary_text = (
    "SN Ia penalized: 99.8%  |  SN II penalized: 97.4%\n"
    "SN contamination in boosted: 0.0%\n"
    "KN rise median: 0.33 mag/d  |  SN Ia rise median: 0.18 mag/d\n"
    "KN decay median: 0.39 mag/d  |  SN Ia decay median: 0.07 mag/d"
)

fig.text(0.5, 0.01, summary_text, ha="center", fontsize=10,
         fontstyle="italic", color="dimgray",
         bbox=dict(boxstyle="round,pad=0.5", facecolor="lightyellow", alpha=0.8))

plt.tight_layout(rect=[0, 0.07, 1, 0.95])

out_path = Path(__file__).resolve().parent.parent.parent / "assets" / "early_rate_discrimination.png"
plt.savefig(out_path, dpi=150, bbox_inches="tight")
print(f"Saved: {out_path}")
plt.close()
